services:
  # Python Backend API
  api:
    build: ./CLI
    container_name: multivol-api
    ports:
      - "5001:5001"
    environment:
      - HOST_PATH=${HOST_PATH} # Valid path to project root on Host, required for DooD
      - API_TOKEN=multivol_default_secret_token
      - APP_PASSWORD=admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access to host Docker
      - ./outputs:/app/outputs
      - ./storage:/app/storage
      - ./volatility3_symbols:/app/volatility3_symbols
      - ./volatility2_profiles:/app/volatility2_profiles
      - ./volatility3_plugins:/app/volatility3_plugins
      - ./volatility3_cache:/app/volatility3_cache

  web:
    build:
      context: ./Web
      args:
        - VITE_API_TOKEN=multivol_default_secret_token
        - VITE_API_URL=http://localhost:5001
    container_name: multivol-web
    ports:
      - "80:80"
    depends_on:
      - api

  mcp:
    build: ./MCP
    container_name: multivol-mcp
    ports:
      - "8000:8000"
    environment:
      - TARGET_URL=http://api
      - TARGET_PORT=5001
      - API_TOKEN=multivol_default_secret_token
    depends_on:
      - api
